on: 
  issues:
    types: [opened, edited, milestoned]

name: Jira issue creationg from git issue

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    - name: Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: create
      id: create
      uses: atlassian/gajira-create@v3
      with:
        project: AD
        issuetype: Task
        summary: ${{ github.event.issue.title  }} 
        description: ${{github.event.issue.body}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
